# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_book_in_stock',
            field=models.IntegerField(default=0, verbose_name='The number of books in stock'),
        ),
    ]
